# Change these first
owner: openupm # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: "[Global] OpenUPM Website"
    url: https://openupm.com
  - name: "[Global] OpenUPM Website Docs"
    url: https://openupm.com/docs/
  - name: "[Global] OpenUPM Website Packages"
    url: https://openupm.com/packages/
  - name: "[Global] OpenUPM Website Package Detail"
    url: https://openupm.com/packages/com.littlebigfun.addressable-importer/
  - name: "[Global] OpenUPM API /site/info"
    url: https://api.openupm.com/site/info
  - name: "[Global] OpenUPM API /packages/extra"
    url: https://api.openupm.com/packages/extra
  - name: "[Global] OpenUPM API /packages/recent"
    url: https://api.openupm.com/packages/recent
  - name: "[Global] OpenUPM API /feeds/updates/rss"
    url: https://api.openupm.com/feeds/updates/rss
  - name: "[Global] OpenUPM API /packages/package-name"
    url: https://api.openupm.com/packages/com.littlebigfun.addressable-importer
  - name: "[Global] OpenUPM Registry /-/all"
    url: https://package.openupm.com/-/all
  - name: "[Global] OpenUPM Registry /package-name"
    url: https://package.openupm.com/com.littlebigfun.addressable-importer
  - name: "[Global] OpenUPM Registry Fetch a Tarball"
    url: https://package.openupm.com:443/com.littlebigfun.addressable-importer/-/com.littlebigfun.addressable-importer-0.9.3.tgz
  - name: "[Global] Unity Registry /package-name"
    url: https://packages.unity.com/com.unity.addressables

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://github.com/openupm.png?size=128
  name: OpenUPM Status
  introTitle: "Uptime monitor and status page for OpenUPM"
  introMessage: Powered by [@upptime](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
